version: '2'
services:        
    nginx:
        container_name: opti_srvWeb
        image: richarvey/nginx-php-fpm:1.3.9
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - /etc/letsencrypt/:/etc/letsencrypt/
            - /srv/docker/log/opti_srvWeb:/var/log/nginx/
        networks: 
            DMZ:
                ipv4_address: 192.168.0.2
    api:
        container_name: opti_api
        image: keydownr/opti_api:latest
        networks: 
            DMZ:
                ipv4_address: 192.168.0.3
    mysql:
        container_name: opti_db
        image: mysql/mysql-server:5.7.20
        ports:
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=MysqlPswd358
        networks: 
            SZ:
                ipv4_address: 192.168.1.2
networks: 
    DMZ:
        driver: bridge
        ipam: 
            driver: default
            config: 
                - subnet: 192.168.0.0/24
                  gateway: 192.168.0.254
    SZ:
        driver: bridge
        ipam: 
            driver: default
            config: 
                - subnet: 192.168.1.0/24
                  gateway: 192.168.1.254
